export const LIKE_MOVIE = "LIKE_MOVIE";
export const BLOCK_MOVIE = "BLOCK_MOVIE";
export const DELETE_LIKED_MOVIE = "DELETE_LIKED_MOVIE";
export const DELETE_BLOCKED_MOVIE = "DELETE_BLOCKED_MOVIE";
export const UNBLOCK_MOVIE = "UNBLOCK_MOIE";
export const STROE_MOVIE_DATA = "STROE_MOVIE_DATA";
export const EXPAND_MOVIE_DATA = "EXPAND_MOVIE_DATA";
export const STORE_MOVIE_DETAILS = "STORE_MOVIE_DETAILS";

