const LIKE_MOVIE = "LIKE_MOVIE";
const BLOCK_MOVIE = "BLOCK_MOVIE";
const DELETE_LIKED_MOVIE = "DELETE_LIKED_MOVIE";
const DELETE_BLOCKED_MOVIE = "DELETE_BLOCKED_MOVIE";
const UNBLOCK_MOVIE = "UNBLOCK_MOIE";
const STROE_MOVIE_DATA = "STROE_MOVIE_DATA";
const EXPAND_MOVIE_DATA = "EXPAND_MOVIE_DATA";

export default {
  LIKE_MOVIE,
  BLOCK_MOVIE,
  DELETE_LIKED_MOVIE,
  DELETE_BLOCKED_MOVIE,
  UNBLOCK_MOVIE,
  STROE_MOVIE_DATA,
  EXPAND_MOVIE_DATA,
};
